# Generated by Django 4.1.7 on 2023-04-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reg_delete_artu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('mail', models.CharField(max_length=50, verbose_name='Почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('details', models.TextField(verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
