# Generated by Django 4.2 on 2023-07-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'Автор/Книга', 'verbose_name_plural': 'Автор/Книга'},
        ),
        migrations.AlterField(
            model_name='base',
            name='name',
            field=models.CharField(blank=True, max_length=77, null=True, verbose_name='name'),
        ),
    ]
