# Generated by Django 4.1.1 on 2023-04-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='test_field',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
